// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod unions;
mod type_aliases;

pub use classes::*;
pub use unions::*;
pub use type_aliases::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {

    AskUserTool(AskUserTool),

    BashBgTool(BashBgTool),

    BashCommandTool(BashCommandTool),

    DependenciesTool(DependenciesTool),

    EditFileTool(EditFileTool),

    FinishTaskTool(FinishTaskTool),

    GitAddTool(GitAddTool),

    GitCommitTool(GitCommitTool),

    GitDiffTool(GitDiffTool),

    GitStatusTool(GitStatusTool),

    McpToolCall(McpToolCall),

    MemoryTool(MemoryTool),

    Message(Message),

    NextStep(NextStep),

    OpenEditorTool(OpenEditorTool),

    ProjectMapTool(ProjectMapTool),

    ReadFileTool(ReadFileTool),

    SearchCodeTool(SearchCodeTool),

    WriteFileTool(WriteFileTool),


    Union17AskUserToolOrBashBgToolOrBashCommandToolOrDependenciesToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrProjectMapToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(Union17AskUserToolOrBashBgToolOrBashCommandToolOrDependenciesToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrProjectMapToolOrReadFileToolOrSearchCodeToolOrWriteFileTool),

}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            StreamTypes::AskUserTool(_) => "AskUserTool",

            StreamTypes::BashBgTool(_) => "BashBgTool",

            StreamTypes::BashCommandTool(_) => "BashCommandTool",

            StreamTypes::DependenciesTool(_) => "DependenciesTool",

            StreamTypes::EditFileTool(_) => "EditFileTool",

            StreamTypes::FinishTaskTool(_) => "FinishTaskTool",

            StreamTypes::GitAddTool(_) => "GitAddTool",

            StreamTypes::GitCommitTool(_) => "GitCommitTool",

            StreamTypes::GitDiffTool(_) => "GitDiffTool",

            StreamTypes::GitStatusTool(_) => "GitStatusTool",

            StreamTypes::McpToolCall(_) => "McpToolCall",

            StreamTypes::MemoryTool(_) => "MemoryTool",

            StreamTypes::Message(_) => "Message",

            StreamTypes::NextStep(_) => "NextStep",

            StreamTypes::OpenEditorTool(_) => "OpenEditorTool",

            StreamTypes::ProjectMapTool(_) => "ProjectMapTool",

            StreamTypes::ReadFileTool(_) => "ReadFileTool",

            StreamTypes::SearchCodeTool(_) => "SearchCodeTool",

            StreamTypes::WriteFileTool(_) => "WriteFileTool",


            StreamTypes::Union17AskUserToolOrBashBgToolOrBashCommandToolOrDependenciesToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrProjectMapToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(_) => "Union17AskUserToolOrBashBgToolOrBashCommandToolOrDependenciesToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrProjectMapToolOrReadFileToolOrSearchCodeToolOrWriteFileTool",


        }
    }
}