// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming union types.

use super::*;
use crate::baml_client::types;
use baml::BamlDecode;

/// Generated from: (Streaming.ReadFileTool | Streaming.WriteFileTool | Streaming.EditFileTool | Streaming.BashCommandTool | Streaming.BashBgTool | Streaming.SearchCodeTool | Streaming.GitStatusTool | Streaming.GitDiffTool | Streaming.GitAddTool | Streaming.GitCommitTool | Streaming.OpenEditorTool | Streaming.AskUserTool | Streaming.FinishTaskTool | Streaming.McpToolCall | Streaming.MemoryTool)
#[derive(Debug, Clone, BamlDecode)]
#[baml(union)]
pub enum Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool
{
    #[baml(name = "ReadFileTool")]
    ReadFileTool(ReadFileTool),

    #[baml(name = "WriteFileTool")]
    WriteFileTool(WriteFileTool),

    #[baml(name = "EditFileTool")]
    EditFileTool(EditFileTool),

    #[baml(name = "BashCommandTool")]
    BashCommandTool(BashCommandTool),

    #[baml(name = "BashBgTool")]
    BashBgTool(BashBgTool),

    #[baml(name = "SearchCodeTool")]
    SearchCodeTool(SearchCodeTool),

    #[baml(name = "GitStatusTool")]
    GitStatusTool(GitStatusTool),

    #[baml(name = "GitDiffTool")]
    GitDiffTool(GitDiffTool),

    #[baml(name = "GitAddTool")]
    GitAddTool(GitAddTool),

    #[baml(name = "GitCommitTool")]
    GitCommitTool(GitCommitTool),

    #[baml(name = "OpenEditorTool")]
    OpenEditorTool(OpenEditorTool),

    #[baml(name = "AskUserTool")]
    AskUserTool(AskUserTool),

    #[baml(name = "FinishTaskTool")]
    FinishTaskTool(FinishTaskTool),

    #[baml(name = "McpToolCall")]
    McpToolCall(McpToolCall),

    #[baml(name = "MemoryTool")]
    MemoryTool(MemoryTool),
}

impl AsRef<Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool> for Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn as_ref(&self) -> &Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
        self
    }
}

impl Default for Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn default() -> Self {
        
           
            Self::ReadFileTool(Default::default())
        
    }
}
