// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct AskUserTool {
    pub tool_name: String,

    pub question: String,
}

impl AsRef<AskUserTool> for AskUserTool {
    fn as_ref(&self) -> &AskUserTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct BashBgTool {
    pub tool_name: String,

    pub name: String,

    pub command: String,
}

impl AsRef<BashBgTool> for BashBgTool {
    fn as_ref(&self) -> &BashBgTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct BashCommandTool {
    pub tool_name: String,

    pub command: String,

    pub description: Option<String>,

    pub timeout: Option<i64>,
}

impl AsRef<BashCommandTool> for BashCommandTool {
    fn as_ref(&self) -> &BashCommandTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct DependenciesTool {
    pub tool_name: String,

    pub path: Option<String>,
}

impl AsRef<DependenciesTool> for DependenciesTool {
    fn as_ref(&self) -> &DependenciesTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct EditFileTool {
    pub tool_name: String,

    pub path: String,

    pub old_string: String,

    pub new_string: String,
}

impl AsRef<EditFileTool> for EditFileTool {
    fn as_ref(&self) -> &EditFileTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct FinishTaskTool {
    pub tool_name: String,

    pub summary: String,
}

impl AsRef<FinishTaskTool> for FinishTaskTool {
    fn as_ref(&self) -> &FinishTaskTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct GitAddTool {
    pub tool_name: String,

    pub paths: Vec<String>,
}

impl AsRef<GitAddTool> for GitAddTool {
    fn as_ref(&self) -> &GitAddTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct GitCommitTool {
    pub tool_name: String,

    pub message: String,
}

impl AsRef<GitCommitTool> for GitCommitTool {
    fn as_ref(&self) -> &GitCommitTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct GitDiffTool {
    pub tool_name: String,

    pub path: Option<String>,

    pub cached: Option<bool>,
}

impl AsRef<GitDiffTool> for GitDiffTool {
    fn as_ref(&self) -> &GitDiffTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct GitStatusTool {
    pub tool_name: String,

    pub dummy: Option<String>,
}

impl AsRef<GitStatusTool> for GitStatusTool {
    fn as_ref(&self) -> &GitStatusTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct McpToolCall {
    pub tool_name: String,

    pub server: String,

    pub tool: String,

    pub arguments: Option<String>,
}

impl AsRef<McpToolCall> for McpToolCall {
    fn as_ref(&self) -> &McpToolCall {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct MemoryTool {
    pub tool_name: String,

    pub operation: Union2KforgetOrKsave,

    pub category: Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference,

    pub section: String,

    pub content: String,

    pub context: Option<String>,

    pub confidence: Union2KconfirmedOrKtentative,
}

impl AsRef<MemoryTool> for MemoryTool {
    fn as_ref(&self) -> &MemoryTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Message {
    pub role: String,

    pub content: String,
}

impl AsRef<Message> for Message {
    fn as_ref(&self) -> &Message {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct NextStep {



    pub situation: String,



    pub task: Vec<String>,



    pub actions: Vec<Union18AskUserToolOrBashBgToolOrBashCommandToolOrDependenciesToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrProjectMapToolOrReadFileToolOrSearchCodeToolOrTaskToolOrWriteFileTool>,


}

impl AsRef<NextStep> for NextStep {
    fn as_ref(&self) -> &NextStep {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct OpenEditorTool {
    pub tool_name: String,

    pub path: String,

    pub line: Option<i64>,
}

impl AsRef<OpenEditorTool> for OpenEditorTool {
    fn as_ref(&self) -> &OpenEditorTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ProjectMapTool {
    pub tool_name: String,

    pub path: Option<String>,
}

impl AsRef<ProjectMapTool> for ProjectMapTool {
    fn as_ref(&self) -> &ProjectMapTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ReadFileTool {
    pub tool_name: String,

    pub path: String,

    pub offset: Option<i64>,

    pub limit: Option<i64>,
}

impl AsRef<ReadFileTool> for ReadFileTool {
    fn as_ref(&self) -> &ReadFileTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SearchCodeTool {
    pub tool_name: String,

    pub query: String,
}

impl AsRef<SearchCodeTool> for SearchCodeTool {
    fn as_ref(&self) -> &SearchCodeTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct TaskTool {
    pub tool_name: String,

    pub operation: Union4KcreateOrKdoneOrKlistOrKupdate,

    pub title: Option<String>,

    pub task_id: Option<i64>,

    pub status: Option<Union4KblockedOrKdoneOrKin_progressOrKtodo>,

    pub priority: Option<Union3KhighOrKlowOrKmedium>,

    pub notes: Option<String>,
}

impl AsRef<TaskTool> for TaskTool {
    fn as_ref(&self) -> &TaskTool {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct WriteFileTool {
    pub tool_name: String,

    pub path: String,

    pub content: String,
}

impl AsRef<WriteFileTool> for WriteFileTool {
    fn as_ref(&self) -> &WriteFileTool {
        self
    }
}
