// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod type_aliases;
mod unions;

pub use classes::*;
pub use enums::*;
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {
    AskUserTool(AskUserTool),

    BashBgTool(BashBgTool),

    BashCommandTool(BashCommandTool),

    EditFileTool(EditFileTool),

    FinishTaskTool(FinishTaskTool),

    GitAddTool(GitAddTool),

    GitCommitTool(GitCommitTool),

    GitDiffTool(GitDiffTool),

    GitStatusTool(GitStatusTool),

    McpToolCall(McpToolCall),

    MemoryTool(MemoryTool),

    Message(Message),

    NextStep(NextStep),

    OpenEditorTool(OpenEditorTool),

    ReadFileTool(ReadFileTool),

    SearchCodeTool(SearchCodeTool),

    WriteFileTool(WriteFileTool),



    Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool),

    Union2KconfirmedOrKtentative(Union2KconfirmedOrKtentative),

    Union2KforgetOrKsave(Union2KforgetOrKsave),

    Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference(Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference),

}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::AskUserTool(_) => "AskUserTool",

            Types::BashBgTool(_) => "BashBgTool",

            Types::BashCommandTool(_) => "BashCommandTool",

            Types::EditFileTool(_) => "EditFileTool",

            Types::FinishTaskTool(_) => "FinishTaskTool",

            Types::GitAddTool(_) => "GitAddTool",

            Types::GitCommitTool(_) => "GitCommitTool",

            Types::GitDiffTool(_) => "GitDiffTool",

            Types::GitStatusTool(_) => "GitStatusTool",

            Types::McpToolCall(_) => "McpToolCall",

            Types::MemoryTool(_) => "MemoryTool",

            Types::Message(_) => "Message",

            Types::NextStep(_) => "NextStep",

            Types::OpenEditorTool(_) => "OpenEditorTool",

            Types::ReadFileTool(_) => "ReadFileTool",

            Types::SearchCodeTool(_) => "SearchCodeTool",

            Types::WriteFileTool(_) => "WriteFileTool",



            Types::Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(_) => "Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool",

            Types::Union2KconfirmedOrKtentative(_) => "Union2KconfirmedOrKtentative",

            Types::Union2KforgetOrKsave(_) => "Union2KforgetOrKsave",

            Types::Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference(_) => "Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference",


        }
    }
}
