// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {

    AskUserTool(AskUserTool),

    BashCommandTool(BashCommandTool),

    EditFileTool(EditFileTool),

    FinishTaskTool(FinishTaskTool),

    GitAddTool(GitAddTool),

    GitCommitTool(GitCommitTool),

    GitDiffTool(GitDiffTool),

    GitStatusTool(GitStatusTool),

    Message(Message),

    NextStep(NextStep),

    OpenEditorTool(OpenEditorTool),

    ReadFileTool(ReadFileTool),

    SearchCodeTool(SearchCodeTool),

    WriteFileTool(WriteFileTool),



    Union12AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(Union12AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool),

}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::AskUserTool(_) => "AskUserTool",

            Types::BashCommandTool(_) => "BashCommandTool",

            Types::EditFileTool(_) => "EditFileTool",

            Types::FinishTaskTool(_) => "FinishTaskTool",

            Types::GitAddTool(_) => "GitAddTool",

            Types::GitCommitTool(_) => "GitCommitTool",

            Types::GitDiffTool(_) => "GitDiffTool",

            Types::GitStatusTool(_) => "GitStatusTool",

            Types::Message(_) => "Message",

            Types::NextStep(_) => "NextStep",

            Types::OpenEditorTool(_) => "OpenEditorTool",

            Types::ReadFileTool(_) => "ReadFileTool",

            Types::SearchCodeTool(_) => "SearchCodeTool",

            Types::WriteFileTool(_) => "WriteFileTool",



            Types::Union12AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(_) => "Union12AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool",


        }
    }
}