// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated union types.

use baml::{BamlEncode, BamlDecode};
use super::*;


/// Generated from: (ReadFileTool | WriteFileTool | EditFileTool | BashCommandTool | BashBgTool | SearchCodeTool | GitStatusTool | GitDiffTool | GitAddTool | GitCommitTool | OpenEditorTool | AskUserTool | FinishTaskTool | McpToolCall | MemoryTool)
#[derive(Debug, Clone, BamlEncode, BamlDecode)]
#[baml(union)]
pub enum Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {

    #[baml(name = "ReadFileTool")]
        ReadFileTool(ReadFileTool),
    
    #[baml(name = "WriteFileTool")]
        WriteFileTool(WriteFileTool),
    
    #[baml(name = "EditFileTool")]
        EditFileTool(EditFileTool),
    
    #[baml(name = "BashCommandTool")]
        BashCommandTool(BashCommandTool),
    
    #[baml(name = "BashBgTool")]
        BashBgTool(BashBgTool),
    
    #[baml(name = "SearchCodeTool")]
        SearchCodeTool(SearchCodeTool),
    
    #[baml(name = "GitStatusTool")]
        GitStatusTool(GitStatusTool),
    
    #[baml(name = "GitDiffTool")]
        GitDiffTool(GitDiffTool),
    
    #[baml(name = "GitAddTool")]
        GitAddTool(GitAddTool),
    
    #[baml(name = "GitCommitTool")]
        GitCommitTool(GitCommitTool),
    
    #[baml(name = "OpenEditorTool")]
        OpenEditorTool(OpenEditorTool),
    
    #[baml(name = "AskUserTool")]
        AskUserTool(AskUserTool),
    
    #[baml(name = "FinishTaskTool")]
        FinishTaskTool(FinishTaskTool),
    
    #[baml(name = "McpToolCall")]
        McpToolCall(McpToolCall),
    
    #[baml(name = "MemoryTool")]
        MemoryTool(MemoryTool),
    
}

impl AsRef<Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool> for Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn as_ref(&self) -> &Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
        self
    }
}

impl Default for Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn default() -> Self {
        
           
            Self::ReadFileTool(Default::default())
        
    }
}


/// Generated from: ("append" | "replace")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union2KappendOrKreplace {

    #[baml(name = "string_append", literal_string = "append")]
    Kappend,
    
    #[baml(name = "string_replace", literal_string = "replace")]
    Kreplace,
    
}

impl AsRef<Union2KappendOrKreplace> for Union2KappendOrKreplace {
    fn as_ref(&self) -> &Union2KappendOrKreplace {
        self
    }
}

impl Default for Union2KappendOrKreplace {
    fn default() -> Self {
        
           
            Self::Kappend
        
    }
}

