// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated union types.

use baml::{BamlEncode, BamlDecode};
use super::*;


/// Generated from: (ReadFileTool | WriteFileTool | EditFileTool | BashCommandTool | BashBgTool | SearchCodeTool | GitStatusTool | GitDiffTool | GitAddTool | GitCommitTool | OpenEditorTool | AskUserTool | FinishTaskTool | McpToolCall)
#[derive(Debug, Clone, BamlEncode, BamlDecode)]
#[baml(union)]
pub enum Union14AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {

    #[baml(name = "ReadFileTool")]
        ReadFileTool(ReadFileTool),
    
    #[baml(name = "WriteFileTool")]
        WriteFileTool(WriteFileTool),
    
    #[baml(name = "EditFileTool")]
        EditFileTool(EditFileTool),
    
    #[baml(name = "BashCommandTool")]
        BashCommandTool(BashCommandTool),
    
    #[baml(name = "BashBgTool")]
        BashBgTool(BashBgTool),
    
    #[baml(name = "SearchCodeTool")]
        SearchCodeTool(SearchCodeTool),
    
    #[baml(name = "GitStatusTool")]
        GitStatusTool(GitStatusTool),
    
    #[baml(name = "GitDiffTool")]
        GitDiffTool(GitDiffTool),
    
    #[baml(name = "GitAddTool")]
        GitAddTool(GitAddTool),
    
    #[baml(name = "GitCommitTool")]
        GitCommitTool(GitCommitTool),
    
    #[baml(name = "OpenEditorTool")]
        OpenEditorTool(OpenEditorTool),
    
    #[baml(name = "AskUserTool")]
        AskUserTool(AskUserTool),
    
    #[baml(name = "FinishTaskTool")]
        FinishTaskTool(FinishTaskTool),
    
    #[baml(name = "McpToolCall")]
        McpToolCall(McpToolCall),
    
}

impl AsRef<Union14AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool> for Union14AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn as_ref(&self) -> &Union14AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
        self
    }
}

impl Default for Union14AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn default() -> Self {
        
           
            Self::ReadFileTool(Default::default())
        
    }
}

