// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated class types.

use baml::{BamlEncode, BamlDecode};
use super::*;




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct AskUserTool {



    pub question: String,


}



impl AsRef<AskUserTool> for AskUserTool {
    fn as_ref(&self) -> &AskUserTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct BashCommandTool {



    pub command: String,


}



impl AsRef<BashCommandTool> for BashCommandTool {
    fn as_ref(&self) -> &BashCommandTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct FinishTaskTool {



    pub summary: String,


}



impl AsRef<FinishTaskTool> for FinishTaskTool {
    fn as_ref(&self) -> &FinishTaskTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Message {



    pub role: String,



    pub content: String,


}



impl AsRef<Message> for Message {
    fn as_ref(&self) -> &Message {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct NextStep {



    pub analysis: String,



    pub plan_updates: Vec<String>,



    pub action: Union7AskUserToolOrBashCommandToolOrFinishTaskToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool,


}



impl AsRef<NextStep> for NextStep {
    fn as_ref(&self) -> &NextStep {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct OpenEditorTool {



    pub path: String,



    pub line: Option<i64>,


}



impl AsRef<OpenEditorTool> for OpenEditorTool {
    fn as_ref(&self) -> &OpenEditorTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ReadFileTool {



    pub path: String,


}



impl AsRef<ReadFileTool> for ReadFileTool {
    fn as_ref(&self) -> &ReadFileTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct SearchCodeTool {



    pub query: String,


}



impl AsRef<SearchCodeTool> for SearchCodeTool {
    fn as_ref(&self) -> &SearchCodeTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct WriteFileTool {



    pub path: String,



    pub content: String,


}



impl AsRef<WriteFileTool> for WriteFileTool {
    fn as_ref(&self) -> &WriteFileTool {
        self
    }
}

