// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated union types.

use super::*;
use baml::{BamlDecode, BamlEncode};

/// Generated from: (ReadFileTool | WriteFileTool | EditFileTool | BashCommandTool | BashBgTool | SearchCodeTool | GitStatusTool | GitDiffTool | GitAddTool | GitCommitTool | OpenEditorTool | AskUserTool | FinishTaskTool | McpToolCall | MemoryTool)
#[derive(Debug, Clone, BamlEncode, BamlDecode)]
#[baml(union)]
pub enum Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool
{
    #[baml(name = "ReadFileTool")]
    ReadFileTool(ReadFileTool),

    #[baml(name = "WriteFileTool")]
    WriteFileTool(WriteFileTool),

    #[baml(name = "EditFileTool")]
    EditFileTool(EditFileTool),

    #[baml(name = "BashCommandTool")]
    BashCommandTool(BashCommandTool),

    #[baml(name = "BashBgTool")]
    BashBgTool(BashBgTool),

    #[baml(name = "SearchCodeTool")]
    SearchCodeTool(SearchCodeTool),

    #[baml(name = "GitStatusTool")]
    GitStatusTool(GitStatusTool),

    #[baml(name = "GitDiffTool")]
    GitDiffTool(GitDiffTool),

    #[baml(name = "GitAddTool")]
    GitAddTool(GitAddTool),

    #[baml(name = "GitCommitTool")]
    GitCommitTool(GitCommitTool),

    #[baml(name = "OpenEditorTool")]
    OpenEditorTool(OpenEditorTool),

    #[baml(name = "AskUserTool")]
    AskUserTool(AskUserTool),

    #[baml(name = "FinishTaskTool")]
    FinishTaskTool(FinishTaskTool),

    #[baml(name = "McpToolCall")]
    McpToolCall(McpToolCall),

    #[baml(name = "MemoryTool")]
    MemoryTool(MemoryTool),
}

impl AsRef<Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool> for Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn as_ref(&self) -> &Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
        self
    }
}

impl Default for Union15AskUserToolOrBashBgToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrMemoryToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn default() -> Self {
        
           
            Self::ReadFileTool(Default::default())
        
    }
}

/// Generated from: ("confirmed" | "tentative")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union2KconfirmedOrKtentative {
    #[baml(name = "string_confirmed", literal_string = "confirmed")]
    Kconfirmed,

    #[baml(name = "string_tentative", literal_string = "tentative")]
    Ktentative,
}

impl AsRef<Union2KconfirmedOrKtentative> for Union2KconfirmedOrKtentative {
    fn as_ref(&self) -> &Union2KconfirmedOrKtentative {
        self
    }
}

impl Default for Union2KconfirmedOrKtentative {
    fn default() -> Self {
        Self::Kconfirmed
    }
}

/// Generated from: ("save" | "forget")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union2KforgetOrKsave {
    #[baml(name = "string_save", literal_string = "save")]
    Ksave,

    #[baml(name = "string_forget", literal_string = "forget")]
    Kforget,
}

impl AsRef<Union2KforgetOrKsave> for Union2KforgetOrKsave {
    fn as_ref(&self) -> &Union2KforgetOrKsave {
        self
    }
}

impl Default for Union2KforgetOrKsave {
    fn default() -> Self {
        Self::Ksave
    }
}

/// Generated from: ("decision" | "pattern" | "preference" | "insight" | "debug")
#[derive(Debug, Clone, BamlEncode, BamlDecode, PartialEq, Eq, Hash)]
#[baml(union)]
pub enum Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference {
    #[baml(name = "string_decision", literal_string = "decision")]
    Kdecision,

    #[baml(name = "string_pattern", literal_string = "pattern")]
    Kpattern,

    #[baml(name = "string_preference", literal_string = "preference")]
    Kpreference,

    #[baml(name = "string_insight", literal_string = "insight")]
    Kinsight,

    #[baml(name = "string_debug", literal_string = "debug")]
    Kdebug,
}

impl AsRef<Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference>
    for Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference
{
    fn as_ref(&self) -> &Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference {
        self
    }
}

impl Default for Union5KdebugOrKdecisionOrKinsightOrKpatternOrKpreference {
    fn default() -> Self {
        Self::Kdecision
    }
}
