// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated union types.

use baml::{BamlEncode, BamlDecode};
use super::*;


/// Generated from: (ReadFileTool | WriteFileTool | EditFileTool | BashCommandTool | SearchCodeTool | GitStatusTool | GitDiffTool | GitAddTool | GitCommitTool | OpenEditorTool | AskUserTool | FinishTaskTool | McpToolCall)
#[derive(Debug, Clone, BamlEncode, BamlDecode)]
#[baml(union)]
pub enum Union13AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {

    #[baml(name = "ReadFileTool")]
        ReadFileTool(ReadFileTool),
    
    #[baml(name = "WriteFileTool")]
        WriteFileTool(WriteFileTool),
    
    #[baml(name = "EditFileTool")]
        EditFileTool(EditFileTool),
    
    #[baml(name = "BashCommandTool")]
        BashCommandTool(BashCommandTool),
    
    #[baml(name = "SearchCodeTool")]
        SearchCodeTool(SearchCodeTool),
    
    #[baml(name = "GitStatusTool")]
        GitStatusTool(GitStatusTool),
    
    #[baml(name = "GitDiffTool")]
        GitDiffTool(GitDiffTool),
    
    #[baml(name = "GitAddTool")]
        GitAddTool(GitAddTool),
    
    #[baml(name = "GitCommitTool")]
        GitCommitTool(GitCommitTool),
    
    #[baml(name = "OpenEditorTool")]
        OpenEditorTool(OpenEditorTool),
    
    #[baml(name = "AskUserTool")]
        AskUserTool(AskUserTool),
    
    #[baml(name = "FinishTaskTool")]
        FinishTaskTool(FinishTaskTool),
    
    #[baml(name = "McpToolCall")]
        McpToolCall(McpToolCall),
    
}

impl AsRef<Union13AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool> for Union13AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn as_ref(&self) -> &Union13AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
        self
    }
}

impl Default for Union13AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool {
    fn default() -> Self {
        
           
            Self::ReadFileTool(Default::default())
        
    }
}


/// Generated from: (string | int | bool | float | string[])
#[derive(Debug, Clone, BamlEncode, BamlDecode)]
#[baml(union)]
pub enum Union5BoolOrFloatOrIntOrListStringOrString {

    #[baml(name = "string")]
        String(String),
    
    #[baml(name = "int")]
        Int(i64),
    
    #[baml(name = "bool")]
        Bool(bool),
    
    #[baml(name = "float")]
        Float(f64),
    
    #[baml(name = "List__string")]
        ListString(Vec<String>),
    
}

impl AsRef<Union5BoolOrFloatOrIntOrListStringOrString> for Union5BoolOrFloatOrIntOrListStringOrString {
    fn as_ref(&self) -> &Union5BoolOrFloatOrIntOrListStringOrString {
        self
    }
}

impl Default for Union5BoolOrFloatOrIntOrListStringOrString {
    fn default() -> Self {
        
           
            Self::String(Default::default())
        
    }
}

