// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::BamlDecode;
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, Default, BamlDecode)]

pub struct AskUserTool {



    pub question: Option<String>,


}



impl AsRef<AskUserTool> for AskUserTool {
    fn as_ref(&self) -> &AskUserTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct BashCommandTool {



    pub command: Option<String>,


}



impl AsRef<BashCommandTool> for BashCommandTool {
    fn as_ref(&self) -> &BashCommandTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct EditFileTool {



    pub path: Option<String>,



    pub old_string: Option<String>,



    pub new_string: Option<String>,


}



impl AsRef<EditFileTool> for EditFileTool {
    fn as_ref(&self) -> &EditFileTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct FinishTaskTool {



    pub summary: Option<String>,


}



impl AsRef<FinishTaskTool> for FinishTaskTool {
    fn as_ref(&self) -> &FinishTaskTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct GitAddTool {



    pub paths: Vec<String>,


}



impl AsRef<GitAddTool> for GitAddTool {
    fn as_ref(&self) -> &GitAddTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct GitCommitTool {



    pub message: Option<String>,


}



impl AsRef<GitCommitTool> for GitCommitTool {
    fn as_ref(&self) -> &GitCommitTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct GitDiffTool {



    pub path: Option<String>,



    pub cached: Option<bool>,


}



impl AsRef<GitDiffTool> for GitDiffTool {
    fn as_ref(&self) -> &GitDiffTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct GitStatusTool {



    pub dummy: Option<String>,


}



impl AsRef<GitStatusTool> for GitStatusTool {
    fn as_ref(&self) -> &GitStatusTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct McpToolCall {



    pub server: Option<String>,



    pub tool: Option<String>,



    pub arguments: Option<String>,


}



impl AsRef<McpToolCall> for McpToolCall {
    fn as_ref(&self) -> &McpToolCall {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct Message {



    pub role: Option<String>,



    pub content: Option<String>,


}



impl AsRef<Message> for Message {
    fn as_ref(&self) -> &Message {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct NextStep {



    pub analysis: Option<String>,



    pub plan_updates: Vec<String>,



    pub action: Option<Union13AskUserToolOrBashCommandToolOrEditFileToolOrFinishTaskToolOrGitAddToolOrGitCommitToolOrGitDiffToolOrGitStatusToolOrMcpToolCallOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool>,


}



impl AsRef<NextStep> for NextStep {
    fn as_ref(&self) -> &NextStep {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct OpenEditorTool {



    pub path: Option<String>,



    pub line: Option<i64>,


}



impl AsRef<OpenEditorTool> for OpenEditorTool {
    fn as_ref(&self) -> &OpenEditorTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct ReadFileTool {



    pub path: Option<String>,



    pub offset: Option<i64>,



    pub limit: Option<i64>,


}



impl AsRef<ReadFileTool> for ReadFileTool {
    fn as_ref(&self) -> &ReadFileTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct SearchCodeTool {



    pub query: Option<String>,


}



impl AsRef<SearchCodeTool> for SearchCodeTool {
    fn as_ref(&self) -> &SearchCodeTool {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode)]

pub struct WriteFileTool {



    pub path: Option<String>,



    pub content: Option<String>,


}



impl AsRef<WriteFileTool> for WriteFileTool {
    fn as_ref(&self) -> &WriteFileTool {
        self
    }
}

