// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod unions;
mod type_aliases;

pub use classes::*;
pub use unions::*;
pub use type_aliases::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {

    AskUserTool(AskUserTool),

    BashCommandTool(BashCommandTool),

    FinishTaskTool(FinishTaskTool),

    Message(Message),

    NextStep(NextStep),

    OpenEditorTool(OpenEditorTool),

    ReadFileTool(ReadFileTool),

    SearchCodeTool(SearchCodeTool),

    WriteFileTool(WriteFileTool),


    Union7AskUserToolOrBashCommandToolOrFinishTaskToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(Union7AskUserToolOrBashCommandToolOrFinishTaskToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool),

}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            StreamTypes::AskUserTool(_) => "AskUserTool",

            StreamTypes::BashCommandTool(_) => "BashCommandTool",

            StreamTypes::FinishTaskTool(_) => "FinishTaskTool",

            StreamTypes::Message(_) => "Message",

            StreamTypes::NextStep(_) => "NextStep",

            StreamTypes::OpenEditorTool(_) => "OpenEditorTool",

            StreamTypes::ReadFileTool(_) => "ReadFileTool",

            StreamTypes::SearchCodeTool(_) => "SearchCodeTool",

            StreamTypes::WriteFileTool(_) => "WriteFileTool",


            StreamTypes::Union7AskUserToolOrBashCommandToolOrFinishTaskToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool(_) => "Union7AskUserToolOrBashCommandToolOrFinishTaskToolOrOpenEditorToolOrReadFileToolOrSearchCodeToolOrWriteFileTool",


        }
    }
}