// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.


/// Wrapper for the `AskUserTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct AskUserToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl AskUserToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("AskUserTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("AskUserTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `question` field builder.
    pub fn property_question(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("question")
            .expect("AskUserTool.question is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `BashBgTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct BashBgToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl BashBgToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("BashBgTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("BashBgTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `name` field builder.
    pub fn property_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("BashBgTool.name is statically defined in .baml and should always be present")
    }


    /// Access the `command` field builder.
    pub fn property_command(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("command")
            .expect("BashBgTool.command is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `BashCommandTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct BashCommandToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl BashCommandToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("BashCommandTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("BashCommandTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `command` field builder.
    pub fn property_command(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("command")
            .expect("BashCommandTool.command is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `EditFileTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct EditFileToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl EditFileToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("EditFileTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("EditFileTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path")
            .expect("EditFileTool.path is statically defined in .baml and should always be present")
    }


    /// Access the `old_string` field builder.
    pub fn property_old_string(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("old_string")
            .expect("EditFileTool.old_string is statically defined in .baml and should always be present")
    }


    /// Access the `new_string` field builder.
    pub fn property_new_string(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("new_string")
            .expect("EditFileTool.new_string is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `FinishTaskTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct FinishTaskToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl FinishTaskToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("FinishTaskTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("FinishTaskTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `summary` field builder.
    pub fn property_summary(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("summary")
            .expect("FinishTaskTool.summary is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `GitAddTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct GitAddToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl GitAddToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("GitAddTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("GitAddTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `paths` field builder.
    pub fn property_paths(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("paths")
            .expect("GitAddTool.paths is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `GitCommitTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct GitCommitToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl GitCommitToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("GitCommitTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("GitCommitTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `message` field builder.
    pub fn property_message(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("message")
            .expect("GitCommitTool.message is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `GitDiffTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct GitDiffToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl GitDiffToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("GitDiffTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("GitDiffTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path")
            .expect("GitDiffTool.path is statically defined in .baml and should always be present")
    }


    /// Access the `cached` field builder.
    pub fn property_cached(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("cached")
            .expect("GitDiffTool.cached is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `GitStatusTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct GitStatusToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl GitStatusToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("GitStatusTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("GitStatusTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `dummy` field builder.
    pub fn property_dummy(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("dummy")
            .expect("GitStatusTool.dummy is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `McpToolCall` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct McpToolCallClassBuilder {
    inner: baml::ClassBuilder,
}

impl McpToolCallClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("McpToolCall is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("McpToolCall.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `server` field builder.
    pub fn property_server(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("server")
            .expect("McpToolCall.server is statically defined in .baml and should always be present")
    }


    /// Access the `tool` field builder.
    pub fn property_tool(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool")
            .expect("McpToolCall.tool is statically defined in .baml and should always be present")
    }


    /// Access the `arguments` field builder.
    pub fn property_arguments(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("arguments")
            .expect("McpToolCall.arguments is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `Message` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct MessageClassBuilder {
    inner: baml::ClassBuilder,
}

impl MessageClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("Message is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `role` field builder.
    pub fn property_role(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("role")
            .expect("Message.role is statically defined in .baml and should always be present")
    }


    /// Access the `content` field builder.
    pub fn property_content(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("content")
            .expect("Message.content is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `NextStep` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct NextStepClassBuilder {
    inner: baml::ClassBuilder,
}

impl NextStepClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("NextStep is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `analysis` field builder.
    pub fn property_analysis(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("analysis")
            .expect("NextStep.analysis is statically defined in .baml and should always be present")
    }


    /// Access the `plan_updates` field builder.
    pub fn property_plan_updates(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("plan_updates")
            .expect("NextStep.plan_updates is statically defined in .baml and should always be present")
    }


    /// Access the `actions` field builder.
    pub fn property_actions(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("actions")
            .expect("NextStep.actions is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `OpenEditorTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct OpenEditorToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl OpenEditorToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("OpenEditorTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("OpenEditorTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path")
            .expect("OpenEditorTool.path is statically defined in .baml and should always be present")
    }


    /// Access the `line` field builder.
    pub fn property_line(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("line")
            .expect("OpenEditorTool.line is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ReadFileTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ReadFileToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl ReadFileToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("ReadFileTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("ReadFileTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path")
            .expect("ReadFileTool.path is statically defined in .baml and should always be present")
    }


    /// Access the `offset` field builder.
    pub fn property_offset(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("offset")
            .expect("ReadFileTool.offset is statically defined in .baml and should always be present")
    }


    /// Access the `limit` field builder.
    pub fn property_limit(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("limit")
            .expect("ReadFileTool.limit is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SearchCodeTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SearchCodeToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl SearchCodeToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("SearchCodeTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("SearchCodeTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `query` field builder.
    pub fn property_query(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("query")
            .expect("SearchCodeTool.query is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `WriteFileTool` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct WriteFileToolClassBuilder {
    inner: baml::ClassBuilder,
}

impl WriteFileToolClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> baml::TypeDef {
        self.inner.as_type()
            .expect("WriteFileTool is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tool_name` field builder.
    pub fn property_tool_name(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("tool_name")
            .expect("WriteFileTool.tool_name is statically defined in .baml and should always be present")
    }


    /// Access the `path` field builder.
    pub fn property_path(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("path")
            .expect("WriteFileTool.path is statically defined in .baml and should always be present")
    }


    /// Access the `content` field builder.
    pub fn property_content(&self) -> baml::ClassPropertyBuilder {
        self.inner.get_property("content")
            .expect("WriteFileTool.content is statically defined in .baml and should always be present")
    }

}

